### ISSUE TITLE
Demo doesn't work

### ISSUE THREAD

**Issue by mjendza** [permitio/mesa-verde-banking-demo#5]
Hey Permit.io and Gabriel,

Demo mentioned in the Read.Me - https://mesa-verde-banking-demo.railway.app/ doesn't work.

I keep finger crossed for the fix ;)

Mateusz

**Comment by orweis** [comment]
Hi @mjendza - thanks for reporting this is a new recently launched demo - I guess there's an issue with its CI/CD 
Will check and update you here :)

**Comment by gemanor** [comment]
It was a typo in the URL, just updated it to https://mesa-verde.up.railway.app/

**Comment by mjendza** [comment]
Now the URL works :) but I'm facing issue to sign up an account 
![image](https://github.com/user-attachments/assets/0e63fd51-2f8a-4ca2-99b1-435a6fbaddcc)

CC: @orweis @gemanor

**Comment by gemanor** [comment]
It should work now :)

**Comment by mjendza** [comment]
sorry - I got the `https://stytch.com/redirect-error` trying to sing-up (first login)
![image](https://github.com/user-attachments/assets/52c18bb3-0598-46aa-9d90-1d45d3556d9e)
